# Generated by Django 5.1.2 on 2024-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="charge_consumption_before_seeding",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Расход агломерационной шихты после высева:",
            ),
        ),
    ]
