# Generated by Django 5.1.2 on 2024-11-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0002_alter_entry_charge_consumption_before_seeding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="text",
            field=models.CharField(
                default="", max_length=100, verbose_name="Название группы расчетов"
            ),
        ),
    ]
