# Generated by Django 5.1.2 on 2024-11-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0003_alter_date_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="text",
            field=models.CharField(
                default="", max_length=100, verbose_name="Добавить дату расчетов"
            ),
        ),
    ]
