# Generated by Django 5.1.2 on 2024-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agglomerates",
            "0007_alter_entry_difference_between_estimated_and_actual_values",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="actual_value_of_agglomeration_output",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Фактическое значение выхода аглоотсева, кг/т",
            ),
        ),
    ]
