# Generated by Django 5.1.2 on 2024-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0008_alter_entry_actual_value_of_agglomeration_output"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enter_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата расчета"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
