# Generated by Django 5.1.2 on 2024-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0009_dateinput"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateEnter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enter_date", models.DateField()),
            ],
        ),
    ]
