# Generated by Django 5.1.2 on 2024-12-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0010_dateenter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DateEnter",
        ),
    ]
