# Generated by Django 5.1.2 on 2024-12-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0011_delete_dateenter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DateInput",
        ),
    ]
