# Generated by Django 5.1.2 on 2024-12-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0013_date_date_enter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="date_enter",
        ),
    ]
