# Generated by Django 5.1.2 on 2024-12-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0017_date_date_enter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="text",
        ),
        migrations.AlterField(
            model_name="date",
            name="date_enter",
            field=models.DateField(blank=True, null=True, verbose_name="Введите дату"),
        ),
    ]
