# Generated by Django 5.1.2 on 2024-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agglomerates", "0018_remove_date_text_alter_date_date_enter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="date_enter",
            field=models.DateField(blank=True, null=True),
        ),
    ]
